exports.seed = async function (knex) {
	// Deletes ALL existing entries
	await knex('movies').del()
	await knex('movies').insert([
		{
			id: 1,
			movie: 'The Player',
			year: 1992,
			director: 'Robert Altman',
			genre: 'Mystery',
		},
		{
			id: 2,
			movie: 'F For Fake',
			year: 1973,
			director: 'Orson Welles',
			genre: 'Documentary',
		},
		{
			id: 3,
			movie: 'Knight of Cups',
			year: 2015,
			director: 'Terrence Malick',
			genre: 'Romance',
		},
		{
			id: 4,
			movie: 'Sunset Boulevard',
			year: 1950,
			director: 'Billy Wilder',
			genre: 'Drama',
		},
		{
			id: 5,
			movie: '8½',
			year: 1963,
			director: 'Federico Fellini',
			genre: 'Drama',
		},
		{
			id: 6,
			movie: 'Scenes from a Marriage',
			year: 1974,
			director: 'Ingmar Bergman',
			genre: 'Romance',
		},
		{
			id: 7,
			movie: 'Inherent Vice',
			year: 2014,
			director: 'Paul Thomas Anderson',
			genre: 'Mystery',
		},
		{
			id: 8,
			movie: 'Heat',
			year: 1995,
			director: 'Michael Mann',
			genre: 'Crime',
		},
		{
			id: 9,
			movie: 'Barton Fink',
			year: 1991,
			director: 'Joel Coen',
			genre: 'Crime',
		},
		{
			id: 10,
			movie: 'Husbands And Wives',
			year: 1992,
			director: 'Woody Allen',
			genre: 'Romance',
		},
		{
			id: 11,
			movie: 'The Brown Bunny',
			year: 2003,
			director: 'Vincent Gallo',
			genre: 'Drama',
		},
		{
			id: 12,
			movie: 'Synecdoche, New York',
			year: 2008,
			director: 'Charlie Kaufman',
			genre: 'Drama',
		},
		{
			id: 13,
			movie: 'A Woman Under The Influence',
			year: 1974,
			director: 'John Cassavetes',
			genre: 'Drama',
		},
		{
			id: 14,
			movie: 'Mulholland Drive',
			year: 2001,
			director: 'David Lynch',
			genre: 'Mystery',
		},
		{
			id: 15,
			movie: 'After Hours',
			year: 1985,
			director: 'Martin Scorsese',
			genre: 'Mystery',
		},
		{
			id: 16,
			movie: 'Rear Window',
			year: 1954,
			director: 'Alfred Hitchcock',
			genre: 'Mystery',
		},
		{
			id: 17,
			movie: 'The Gleaners and I',
			year: 2000,
			director: 'Agnès Varda',
			genre: 'Documentary',
		},
		{
			id: 18,
			movie: 'Eyes Wide Shut',
			year: 1999,
			director: 'Stanley Kubrick',
			genre: 'Mystery',
		},
		{
			id: 19,
			movie: 'Rushmore',
			year: 1998,
			director: 'Wes Anderson',
			genre: 'Drama',
		},
		{
			id: 20,
			movie: 'Brief Encounter',
			year: 1945,
			director: 'David Lean',
			genre: 'Romance',
		},
	])
}
